[mysqld]
basedir="C:/Program Files/MySQL/MySQL Server 8.4"
datadir="C:/Users/Mrs. Shin Hye Jung/OneDrive/Documents/brd/NEO/neophoto/mysql-data"
port=3306
socket="C:/Users/Mrs. Shin Hye Jung/OneDrive/Documents/brd/NEO/neophoto/mysql-data/mysql.sock"
skip-networking=0
bind-address=127.0.0.1
sql_mode=NO_ENGINE_SUBSTITUTION
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
log-error="C:/Users/Mrs. Shin Hye Jung/OneDrive/Documents/brd/NEO/neophoto/mysql-data/mysql.err"

[client]
socket="C:/Users/Mrs. Shin Hye Jung/OneDrive/Documents/brd/NEO/neophoto/mysql-data/mysql.sock"
